"use server";
import prisma from "@/lib/db";
import { z } from "zod";
import { auth } from "@/lib/auth";
export async function getCaseCard(
  search?: string,
  page?: number,
  pageSize?: number
) {
  try {
    // Default values for pagination
    page = page || 1;
    pageSize = pageSize || 10;

    const where = search
      ? {
          OR: [
            { historyCode: { contains: search, mode: "insensitive" } },
            // { patientTypeData: { contains: search, mode: "insensitive" } },
          ],
        }
      : {};

    const totalRows = await prisma.history.count({ where });
    const totalPages = Math.ceil(totalRows / pageSize);

    const histories = await prisma.history.findMany({
      where,
      select: {
        id: true,
        student: { select: { wdt_ID: true, name: true } },
        historyCode: true,
        patientTypeData: true,
        createdAt: true,
      },
      skip: (page - 1) * pageSize,
      take: pageSize,
    });

    return {
      data: histories,
      pagination: {
        currentPage: page,
        totalPages: totalPages,
        itemsPerPage: pageSize,
        totalRecords: totalRows,
        hasNextPage: page < totalPages,
        hasPreviousPage: page > 1,
      },
    };
  } catch (error) {
    console.error("Error fetching case cards:", error);
    throw new Error("Failed to fetch case cards");
  }
}

export async function createCaseCard(
  studentId: number,
  patientTypeData: string
) {
  try {
    const newCase = await prisma.history.create({
      data: {
        studentId,
        patientTypeData,
        // historyCode will be auto-generated by @default(cuid())
      },
    });
    return { message: "Case card created successfully" };
  } catch (error) {
    console.error("Error creating case card:", error);
    return { message: "Failed to create case card" };
  }
}

export async function deleteCaseCard(id: string) {
  try {
    await prisma.history.delete({
      where: { id },
    });
    return { message: "Case card deleted successfully" };
  } catch (error) {
    console.error("Error deleting case card:", error);
    return { message: "Failed to delete case card" };
  }
}

export async function changeCaseStatus(id: string) {}

export async function getallDiagnosisPerCase() {}
export async function createDiagnosis() {}
export async function deleteDiagnosis() {}

export async function getallObservationPerCase() {}
export async function createObservation() {}
export async function deleteObservation() {}

export async function getallTreatmentPerCase() {}
export async function createTreatment() {}
export async function deleteTreatment() {}
